/*
SQLyog Community
MySQL - 10.1.40-MariaDB-0ubuntu0.18.04.1 : Database - gampe_ivr
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`gampe_ivr` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `gampe_ivr`;

/*Table structure for table `reporteConsultas` */

DROP TABLE IF EXISTS `reporteConsultas`;

CREATE TABLE `reporteConsultas` (
  `TELEFONO_CONSULTA` int(11) DEFAULT NULL,
  `NUMDOCUMENTO_CONSULTA` varchar(20) DEFAULT NULL,
  `IDINCIDENCIA` varchar(30) DEFAULT NULL,
  `FECHA_INCIDENCIA` varchar(20) DEFAULT NULL,
  `HORA_INCIDENCIA` varchar(10) DEFAULT NULL,
  `USUARIO_INCIDENCIA` varchar(20) DEFAULT NULL,
  `CODCLIENTE` int(11) DEFAULT NULL,
  `NODO` varchar(2) DEFAULT NULL,
  `TROBA` varchar(4) DEFAULT NULL,
  `AMPLIFICADOR` varchar(2) DEFAULT NULL,
  `FECHA_HORA_CONSULTA` varchar(20) DEFAULT NULL,
  `SISTEMA` varchar(10) DEFAULT NULL,
  `RESULTADO` varchar(10) DEFAULT NULL,
  UNIQUE KEY `TELEFONO_CONSULTA_2` (`TELEFONO_CONSULTA`,`FECHA_HORA_CONSULTA`),
  KEY `TELEFONO_CONSULTA` (`TELEFONO_CONSULTA`),
  KEY `NUMDOCUMENTO_CONSULTA` (`NUMDOCUMENTO_CONSULTA`),
  KEY `NODO` (`NODO`),
  KEY `TROBA` (`TROBA`),
  KEY `AMPLIFICADOR` (`AMPLIFICADOR`),
  KEY `FECHA_HORA_CONSULTA` (`FECHA_HORA_CONSULTA`),
  KEY `RESULTADO` (`RESULTADO`),
  KEY `IDDINCIDENCIA` (`IDINCIDENCIA`),
  KEY `FECHA_INCIDENCIA` (`FECHA_INCIDENCIA`),
  KEY `HORA_INCIDENCIA` (`HORA_INCIDENCIA`),
  KEY `USUARIO_INCIDENCIA` (`USUARIO_INCIDENCIA`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

/*Table structure for table `reporteConsultas_historico` */

DROP TABLE IF EXISTS `reporteConsultas_historico`;

CREATE TABLE `reporteConsultas_historico` (
  `TELEFONO_CONSULTA` int(11) DEFAULT NULL,
  `NUMDOCUMENTO_CONSULTA` varchar(20) DEFAULT NULL,
  `IDINCIDENCIA` varchar(30) DEFAULT NULL,
  `FECHA_INCIDENCIA` varchar(20) DEFAULT NULL,
  `HORA_INCIDENCIA` varchar(10) DEFAULT NULL,
  `USUARIO_INCIDENCIA` varchar(20) DEFAULT NULL,
  `CODCLIENTE` int(11) DEFAULT NULL,
  `NODO` varchar(2) DEFAULT NULL,
  `TROBA` varchar(4) DEFAULT NULL,
  `AMPLIFICADOR` varchar(2) DEFAULT NULL,
  `FECHA_HORA_CONSULTA` varchar(20) DEFAULT NULL,
  `SISTEMA` varchar(10) DEFAULT NULL,
  `RESULTADO` varchar(10) DEFAULT NULL,
  UNIQUE KEY `TELEFONO_CONSULTA_2` (`TELEFONO_CONSULTA`,`FECHA_HORA_CONSULTA`),
  KEY `TELEFONO_CONSULTA` (`TELEFONO_CONSULTA`),
  KEY `NUMDOCUMENTO_CONSULTA` (`NUMDOCUMENTO_CONSULTA`),
  KEY `NODO` (`NODO`),
  KEY `TROBA` (`TROBA`),
  KEY `AMPLIFICADOR` (`AMPLIFICADOR`),
  KEY `FECHA_HORA_CONSULTA` (`FECHA_HORA_CONSULTA`),
  KEY `RESULTADO` (`RESULTADO`),
  KEY `IDDINCIDENCIA` (`IDINCIDENCIA`),
  KEY `FECHA_INCIDENCIA` (`FECHA_INCIDENCIA`),
  KEY `HORA_INCIDENCIA` (`HORA_INCIDENCIA`),
  KEY `USUARIO_INCIDENCIA` (`USUARIO_INCIDENCIA`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

/*Table structure for table `reporteTickets` */

DROP TABLE IF EXISTS `reporteTickets`;

CREATE TABLE `reporteTickets` (
  `IDINCIDENCIA` int(11) NOT NULL,
  `CODINCIDENCIA` varchar(30) DEFAULT NULL,
  `FECHA_INICIO` varchar(20) DEFAULT NULL,
  `HORA_INICIO` varchar(10) DEFAULT NULL,
  `FECHA_FIN` varchar(20) DEFAULT NULL,
  `HORA_FIN` varchar(10) DEFAULT NULL,
  `USUARIO_CREACION` varchar(20) DEFAULT NULL,
  `USUARIO_MODIFICACION` varchar(20) DEFAULT NULL,
  `DURACION` int(11) DEFAULT NULL,
  `LOCUCION` varchar(50) DEFAULT NULL,
  `TIPO` varchar(100) DEFAULT NULL,
  `CMTS` varchar(100) DEFAULT NULL,
  `INTERFAZ` varchar(50) DEFAULT NULL,
  `NODO` varchar(2) DEFAULT NULL,
  `TROBA` varchar(4) DEFAULT NULL,
  `AMPLIFICADOR` varchar(2) DEFAULT NULL,
  `ESTADO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`IDINCIDENCIA`),
  KEY `FECHA_INICIO` (`FECHA_INICIO`),
  KEY `HORA_INICIO` (`HORA_INICIO`),
  KEY `FECHA_FIN` (`FECHA_FIN`),
  KEY `HORA_FIN` (`HORA_FIN`),
  KEY `USUARIO_CREACION` (`USUARIO_CREACION`),
  KEY `USUARIO_MODIFICACION` (`USUARIO_MODIFICACION`),
  KEY `LOCUCION` (`LOCUCION`),
  KEY `CMTS` (`CMTS`),
  KEY `INTERFAZ` (`INTERFAZ`),
  KEY `NODO` (`NODO`),
  KEY `TROBA` (`TROBA`),
  KEY `AMPLIFICADOR` (`AMPLIFICADOR`),
  KEY `CODINCIDENCIA` (`CODINCIDENCIA`),
  KEY `ESTADO` (`ESTADO`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

/*Table structure for table `reporteTickets_c` */

DROP TABLE IF EXISTS `reporteTickets_c`;

CREATE TABLE `reporteTickets_c` (
  `IDINCIDENCIA` int(11) NOT NULL,
  `CODINCIDENCIA` varchar(30) DEFAULT NULL,
  `FECHA_INICIO` varchar(20) DEFAULT NULL,
  `HORA_INICIO` varchar(10) DEFAULT NULL,
  `FECHA_FIN` varchar(20) DEFAULT NULL,
  `HORA_FIN` varchar(10) DEFAULT NULL,
  `USUARIO_CREACION` varchar(20) DEFAULT NULL,
  `USUARIO_MODIFICACION` varchar(20) DEFAULT NULL,
  `DURACION` int(11) DEFAULT NULL,
  `LOCUCION` varchar(50) DEFAULT NULL,
  `TIPO` varchar(100) DEFAULT NULL,
  `CMTS` varchar(100) DEFAULT NULL,
  `INTERFAZ` varchar(50) DEFAULT NULL,
  `NODO` varchar(2) DEFAULT NULL,
  `TROBA` varchar(4) DEFAULT NULL,
  `AMPLIFICADOR` varchar(2) DEFAULT NULL,
  `ESTADO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`IDINCIDENCIA`),
  KEY `FECHA_INICIO` (`FECHA_INICIO`),
  KEY `HORA_INICIO` (`HORA_INICIO`),
  KEY `FECHA_FIN` (`FECHA_FIN`),
  KEY `HORA_FIN` (`HORA_FIN`),
  KEY `USUARIO_CREACION` (`USUARIO_CREACION`),
  KEY `USUARIO_MODIFICACION` (`USUARIO_MODIFICACION`),
  KEY `LOCUCION` (`LOCUCION`),
  KEY `CMTS` (`CMTS`),
  KEY `INTERFAZ` (`INTERFAZ`),
  KEY `NODO` (`NODO`),
  KEY `TROBA` (`TROBA`),
  KEY `AMPLIFICADOR` (`AMPLIFICADOR`),
  KEY `CODINCIDENCIA` (`CODINCIDENCIA`),
  KEY `ESTADO` (`ESTADO`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
