/*
SQLyog Community
MySQL - 10.1.40-MariaDB-0ubuntu0.18.04.1 : Database - z_new_cms
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`z_new_cms` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `z_new_cms`;

/*Table structure for table `clientesm1_xy` */

DROP TABLE IF EXISTS `clientesm1_xy`;

CREATE TABLE `clientesm1_xy` (
  `servicio` int(11) NOT NULL,
  `desdpt` varchar(100) DEFAULT NULL,
  `despvc` varchar(100) DEFAULT NULL,
  `desdtt` varchar(100) DEFAULT NULL,
  `nodo` varchar(2) DEFAULT NULL,
  `plano` varchar(4) DEFAULT NULL,
  `CONCATEN` varchar(100) DEFAULT NULL,
  `NMTIPVIA_TDP` varchar(20) DEFAULT NULL,
  `NOM_VIA` varchar(100) DEFAULT NULL,
  `NUM_PUER` varchar(20) DEFAULT NULL,
  `NMTIPINT` varchar(20) DEFAULT NULL,
  `NUM_INT` varchar(20) DEFAULT NULL,
  `NMTIPVIV` varchar(20) DEFAULT NULL,
  `NOM_VIV` varchar(100) DEFAULT NULL,
  `MZ_NORM` varchar(20) DEFAULT NULL,
  `NUM_LOTE` varchar(20) DEFAULT NULL,
  `NMTIPURB_TDP` varchar(20) DEFAULT NULL,
  `URB_CONC` varchar(100) DEFAULT NULL,
  `x` varchar(30) DEFAULT NULL,
  `y` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`servicio`),
  KEY `nodo` (`nodo`),
  KEY `plano` (`plano`),
  KEY `via` (`NOM_VIA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `cms_tiporeq_motivo` */

DROP TABLE IF EXISTS `cms_tiporeq_motivo`;

CREATE TABLE `cms_tiporeq_motivo` (
  `cabecera` int(11) DEFAULT NULL,
  `oficina` varchar(3) DEFAULT NULL,
  `grupo_req` varchar(2) DEFAULT NULL,
  `des_grupo_req` varchar(70) DEFAULT NULL,
  `tipo_req` varchar(2) DEFAULT NULL,
  `des_tipo_req` varchar(70) DEFAULT NULL,
  `motivo` varchar(4) DEFAULT NULL,
  `des_motivo` varchar(70) DEFAULT NULL,
  `ruta` int(11) DEFAULT NULL,
  `des_ruta` varchar(70) DEFAULT NULL,
  `estacion` varchar(20) DEFAULT NULL,
  `estado` varchar(3) DEFAULT NULL,
  `ind_apro_fact` varchar(3) DEFAULT NULL,
  KEY `tipo_req` (`tipo_req`),
  KEY `motivo` (`motivo`),
  KEY `grupo_req` (`grupo_req`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

/*Table structure for table `planta_clarita` */

DROP TABLE IF EXISTS `planta_clarita`;

CREATE TABLE `planta_clarita` (
  `CLIENTE` int(10) DEFAULT NULL,
  `CUENTA` int(10) DEFAULT NULL,
  `SERVICIO` varchar(20) NOT NULL,
  `CON_SRV` int(11) DEFAULT NULL,
  `CLASESRV` varchar(2) DEFAULT NULL,
  `TIPOSRV` int(11) DEFAULT NULL,
  `CATEGORIA` varchar(3) DEFAULT NULL,
  `OFI_CLI` varchar(3) DEFAULT NULL,
  `OFI_SRV` varchar(3) DEFAULT NULL,
  `CODDPT` varchar(3) DEFAULT NULL,
  `DESDPT` varchar(15) DEFAULT NULL,
  `CODPVC` varchar(3) DEFAULT NULL,
  `DESPVC` varchar(30) DEFAULT NULL,
  `CODDTT` varchar(3) DEFAULT NULL,
  `DESDTT` varchar(40) DEFAULT NULL,
  `INDFACT` varchar(2) DEFAULT NULL,
  `NODO` varchar(4) DEFAULT NULL,
  `DESNODO` varchar(30) DEFAULT NULL,
  `PLANO` varchar(5) DEFAULT NULL,
  `XIND_VIP` varchar(1) DEFAULT NULL,
  `TIPO_DOCUM` varchar(2) DEFAULT NULL,
  `NUMERORUC` varchar(12) DEFAULT NULL,
  `NUMERODOC` varchar(10) DEFAULT NULL,
  `TELEFCL1` varchar(15) DEFAULT NULL,
  `TELEFCL2` varchar(15) DEFAULT NULL,
  `TELEFCL3` varchar(15) DEFAULT NULL,
  `PETICATIS` varchar(20) DEFAULT NULL,
  `SEGMCLIENT` varchar(10) DEFAULT NULL,
  `ESTADODUNA` varchar(15) DEFAULT NULL,
  `NOMBRE` varchar(50) DEFAULT NULL,
  `APE_PAT` varchar(50) DEFAULT NULL,
  `APE_MAT` varchar(40) DEFAULT NULL,
  `CODNIT` varchar(10) DEFAULT NULL,
  `UBIGEOGIS` varchar(10) DEFAULT NULL,
  `DESUBIGEGI` varchar(40) DEFAULT NULL,
  `CODLEX` varchar(10) DEFAULT NULL,
  `CODTAP` varchar(10) DEFAULT NULL,
  `CODBOR` varchar(10) DEFAULT NULL,
  `DIREC_INST` varchar(90) DEFAULT NULL,
  `IND_DUO` varchar(10) DEFAULT NULL,
  `tipo_linea` varchar(6) DEFAULT NULL,
  `telef_ip` varchar(10) DEFAULT NULL,
  `prom_linea` varchar(47) DEFAULT NULL,
  `des_prom_linea` varchar(60) DEFAULT NULL,
  `nodeid` varchar(10) DEFAULT NULL,
  `veloc_cms` int(10) DEFAULT NULL,
  `tiptec` varchar(50) DEFAULT NULL,
  `UBIPLAN` varchar(9) DEFAULT NULL,
  `PAIS` varchar(4) DEFAULT NULL,
  `UBIGEO` varchar(6) DEFAULT NULL,
  `ZONAL_ANT` varchar(3) DEFAULT NULL,
  `REGION` varchar(8) DEFAULT NULL,
  `ZONAL_NEW` varchar(10) DEFAULT NULL,
  `IND_DUNA` varchar(10) DEFAULT NULL,
  `AÑO_DUN` varchar(6) DEFAULT NULL,
  `CRUCE` varchar(4) DEFAULT NULL,
  `PAQUETE` varchar(15) DEFAULT NULL,
  `PAQUETE1` varchar(15) DEFAULT NULL,
  `SUB_NEG` varchar(4) DEFAULT NULL,
  `PROVEEDOR` varchar(4) DEFAULT NULL,
  `TECNOLOGIA` varchar(10) DEFAULT NULL,
  `PERU8K` varchar(7) DEFAULT NULL,
  `MARCAA` varchar(3) DEFAULT NULL,
  `CND_SRV_09` int(11) DEFAULT NULL,
  `CND_SRV_10` int(11) DEFAULT NULL,
  `CND_SRV_11` int(11) DEFAULT NULL,
  `EXCLUSANT` varchar(50) DEFAULT NULL,
  `PROV_ANT` varchar(12) DEFAULT NULL,
  `NEGO_ANT` varchar(10) DEFAULT NULL,
  `CSER_ANT` varchar(2) DEFAULT NULL,
  `PAQU_ANT` varchar(15) DEFAULT NULL,
  `PAQU1_ANT` varchar(10) DEFAULT NULL,
  `SEGMENTO` varchar(15) DEFAULT NULL,
  `SEGMENTO0` varchar(15) DEFAULT NULL,
  `EX_CTA` varchar(13) DEFAULT NULL,
  `MARCA_SUS` int(11) DEFAULT NULL,
  `EXCLU_SUS` varchar(32) DEFAULT NULL,
  `EX_BJ_INCO` varchar(50) DEFAULT NULL,
  `IND_EXCLUS` varchar(46) DEFAULT NULL,
  `SEG_CMS` varchar(2) DEFAULT NULL,
  `JEFCOM` varchar(10) DEFAULT NULL,
  `EECC` varchar(8) DEFAULT NULL,
  `REGION_COC` varchar(8) DEFAULT NULL,
  `ZON_REGION` varchar(4) DEFAULT NULL,
  `PREM_MAS` varchar(7) DEFAULT NULL,
  `DET_REGION` varchar(15) DEFAULT NULL,
  `JEF_REGION` varchar(8) DEFAULT NULL,
  `SEG_SLAS` varchar(11) DEFAULT NULL,
  `TOP_NOTOP` varchar(17) DEFAULT NULL,
  `JEFATU_NUE` varchar(4) DEFAULT NULL,
  `CLIEN_SRV` varchar(15) DEFAULT NULL,
  `MICROZONA` varchar(10) DEFAULT NULL,
  `LLAVE_UBIG` varchar(15) DEFAULT NULL,
  `TERRENO` varchar(15) DEFAULT NULL,
  `EXCLUYE` varchar(1) DEFAULT NULL,
  `IND_VIP` varchar(1) DEFAULT NULL,
  `TELEFONO` int(11) DEFAULT NULL,
  `TIPO` varchar(10) DEFAULT NULL,
  `DIRECCION` varchar(75) DEFAULT NULL,
  `IP` varchar(20) DEFAULT NULL,
  `MACADDRESS` varchar(20) DEFAULT NULL,
  `CMTS` varchar(20) DEFAULT NULL,
  `TEC` varchar(5) DEFAULT NULL,
  `DIGITALIZA` varchar(2) DEFAULT NULL,
  `PAQUETE_HD` varchar(2) DEFAULT NULL,
  `SERVPACK` varchar(50) DEFAULT NULL,
  `VEL_SERVPA` varchar(10) DEFAULT NULL,
  `TIPO_VIA` varchar(4) DEFAULT NULL,
  `VIA` varchar(39) DEFAULT NULL,
  `NRO` varchar(6) DEFAULT NULL,
  `PISO` varchar(4) DEFAULT NULL,
  `INTERIOR` varchar(7) DEFAULT NULL,
  `MZ` varchar(7) DEFAULT NULL,
  `LT` varchar(7) DEFAULT NULL,
  `tipourbani` varchar(6) DEFAULT NULL,
  `urbanizaci` varchar(32) DEFAULT NULL,
  `TIPOPERU8K` varchar(20) DEFAULT NULL,
  `CLIENCCM1` varchar(2) DEFAULT NULL,
  `VOZIP` varchar(2) DEFAULT NULL,
  `PRODCOMER` varchar(100) DEFAULT NULL,
  `VEL_PRODCO` varchar(50) DEFAULT NULL,
  `DIGITAL2` int(11) DEFAULT NULL,
  `DIG_FECHA` varchar(20) DEFAULT NULL,
  `DIG_ESTADO` varchar(18) DEFAULT NULL,
  `DECO_ACT` int(11) DEFAULT NULL,
  `DECO_SUSP` int(11) DEFAULT NULL,
  `TIPREQ_PED` varchar(10) DEFAULT NULL,
  `proceso` date DEFAULT NULL,
  `FECHA_CARGA` char(10) DEFAULT NULL,
  `UNICO` char(2) CHARACTER SET utf8 DEFAULT NULL,
  `numcoo_x` varchar(30) DEFAULT NULL,
  `numcoo_y` varchar(30) DEFAULT NULL,
  `fuentexy` varchar(30) DEFAULT NULL,
  `nodotroba` varchar(10) DEFAULT NULL,
  `naked` varchar(20) DEFAULT NULL,
  UNIQUE KEY `SERVICIO` (`SERVICIO`),
  KEY `CLIENTE` (`CLIENTE`),
  KEY `CLASESRV` (`CLASESRV`),
  KEY `TIPOSRV` (`TIPOSRV`),
  KEY `OFI_CLI` (`OFI_CLI`),
  KEY `DESDPT` (`DESDPT`),
  KEY `CODDPT` (`CODDPT`),
  KEY `CODPVC` (`CODPVC`),
  KEY `DESPVC` (`DESPVC`),
  KEY `CODDTT` (`CODDTT`),
  KEY `DESDTT` (`DESDTT`),
  KEY `NODO` (`NODO`),
  KEY `PLANO` (`PLANO`),
  KEY `TELEFCL1` (`TELEFCL1`),
  KEY `TELEFCL2` (`TELEFCL2`),
  KEY `TELEFCL3` (`TELEFCL3`),
  KEY `UNICO` (`UNICO`),
  KEY `NOMBRE` (`NOMBRE`),
  KEY `CUENTA` (`CUENTA`),
  KEY `APE_MAT` (`APE_MAT`),
  KEY `APE_PAT` (`APE_PAT`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `planta_clarita_edificios` */

DROP TABLE IF EXISTS `planta_clarita_edificios`;

CREATE TABLE `planta_clarita_edificios` (
  `item` int(11) NOT NULL AUTO_INCREMENT,
  `desdtt` varchar(50) DEFAULT NULL,
  `via` varchar(39) DEFAULT NULL,
  `nro` int(11) DEFAULT NULL,
  `encargado` varchar(150) DEFAULT NULL,
  `telcontac` varchar(15) DEFAULT NULL,
  `carta` varchar(10) DEFAULT NULL,
  `presidente` varchar(150) DEFAULT NULL,
  `telpresi` varchar(40) DEFAULT NULL,
  `dia` varchar(20) DEFAULT NULL,
  `horaini` varchar(5) DEFAULT NULL,
  `horafin` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`item`),
  UNIQUE KEY `ubigeo` (`desdtt`,`via`,`nro`),
  KEY `coddtt` (`desdtt`),
  KEY `via` (`via`),
  KEY `nro` (`nro`),
  KEY `encargado` (`encargado`),
  KEY `telcontac` (`telcontac`),
  KEY `carta` (`carta`)
) ENGINE=InnoDB AUTO_INCREMENT=19822 DEFAULT CHARSET=latin1;

/*Table structure for table `prov_liq_catv_pais` */

DROP TABLE IF EXISTS `prov_liq_catv_pais`;

CREATE TABLE `prov_liq_catv_pais` (
  `codigo_req` int(11) DEFAULT NULL,
  `codigo_del_grupo_req` varchar(2) DEFAULT NULL,
  `codigo_tipo_req` varchar(2) DEFAULT NULL,
  `codigo_motivo_req` varchar(4) DEFAULT NULL,
  `codigo_del_cliente` int(11) DEFAULT NULL,
  `apellido_paterno` varchar(35) DEFAULT NULL,
  `apellido_materno` varchar(35) DEFAULT NULL,
  `nombres` varchar(30) DEFAULT NULL,
  `indicador_vip` varchar(10) DEFAULT NULL,
  `categoria_cliente` varchar(50) DEFAULT NULL,
  `codigo_del_servicio` int(11) DEFAULT NULL,
  `clase_de_servicio` varchar(100) DEFAULT NULL,
  `categoria_de_servicio` varchar(2) DEFAULT NULL,
  `oficina_administrativa` varchar(3) DEFAULT NULL,
  `departamento` varchar(3) DEFAULT NULL,
  `provincia` varchar(3) DEFAULT NULL,
  `distrito` varchar(3) DEFAULT NULL,
  `tipo_de_via` varchar(2) DEFAULT NULL,
  `nombre_de_la_via` varchar(30) DEFAULT NULL,
  `numero` int(11) DEFAULT NULL,
  `piso` varchar(2) DEFAULT NULL,
  `interior` varchar(5) DEFAULT NULL,
  `manzana` varchar(5) DEFAULT NULL,
  `lote` varchar(5) DEFAULT NULL,
  `nodo` varchar(2) DEFAULT NULL,
  `plano` varchar(4) DEFAULT NULL,
  `sector` varchar(5) DEFAULT NULL,
  `troba` varchar(4) DEFAULT NULL,
  `lex` varchar(4) DEFAULT NULL,
  `tap` varchar(4) DEFAULT NULL,
  `borne` varchar(4) DEFAULT NULL,
  `estacion` varchar(8) DEFAULT NULL,
  `situacion` varchar(4) DEFAULT NULL,
  `estado` varchar(1) DEFAULT NULL,
  `fecha_registro` varchar(20) DEFAULT NULL,
  `usuario_generacion` varchar(12) DEFAULT NULL,
  `ot` int(11) DEFAULT NULL,
  `fecha_asignacion` varchar(20) DEFAULT NULL,
  `estado_ot` varchar(1) DEFAULT NULL,
  `contrata` int(11) DEFAULT NULL,
  `tecnico` varchar(12) DEFAULT NULL,
  `codigo_de_liquidacion` varchar(12) DEFAULT NULL,
  `fecha_liquidacion` datetime DEFAULT NULL,
  `fecha_programacion` datetime DEFAULT NULL,
  `fecha_informacion` datetime DEFAULT NULL,
  `fecha_llegada` datetime DEFAULT NULL,
  `cross_cms` varchar(20) DEFAULT NULL,
  `sit_envio_actu` varchar(50) DEFAULT NULL,
  `ind_paquete` varchar(30) DEFAULT NULL,
  `tipvis_gestel` varchar(30) DEFAULT NULL,
  `tipvis_cms` varchar(30) DEFAULT NULL,
  `cod_sol_pai` varchar(30) DEFAULT NULL,
  `stdo_sol_pai` varchar(30) DEFAULT NULL,
  `fecha_reg_pai` datetime DEFAULT NULL,
  `ind_pos_fraude` varchar(30) DEFAULT NULL,
  `cod_mot_pos_fraude` varchar(10) DEFAULT NULL,
  `desc_mot_pos_fraude` varchar(100) DEFAULT NULL,
  `nro_ooss_gestel` varchar(30) DEFAULT NULL,
  `stdo_ooss_gestel` varchar(20) DEFAULT NULL,
  `desc_stdo_ooss_gestel` varchar(100) DEFAULT NULL,
  `tip_paquete` varchar(30) DEFAULT NULL,
  `cod_cmts` varchar(30) DEFAULT NULL,
  `desc_cmts2` varchar(100) DEFAULT NULL,
  `peticion_atis` varchar(30) DEFAULT NULL,
  `telefono_de_contacto` varchar(10) DEFAULT NULL,
  `celular_de_contacto` varchar(10) DEFAULT NULL,
  UNIQUE KEY `NewIndex1` (`codigo_req`),
  KEY `NewIndex2` (`codigo_del_cliente`),
  KEY `NewIndex3` (`ot`),
  KEY `idx_servicio` (`codigo_del_servicio`),
  KEY `fechaderegistro` (`fecha_registro`),
  KEY `nodo` (`nodo`),
  KEY `troba` (`troba`),
  KEY `lex` (`lex`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
